Unifac.BlueYonder.Web.ReportSite/Models/BillofLading/BillofLadingModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Unifac.BlueYonder.Web.ReportSite.Models.BillofLading
{
    public class BillofLadingModel
    {
        public string billofladingID { get; set; }
    }
}

Unifac.BlueYonder.Web.ReportSite/Models/ErrorViewModel.cs
using System;

namespace Unifac.BlueYonder.Web.ReportSite.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Unifac.BlueYonder.Web.ReportSite/Models/Orders/OrdersModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Unifac.BlueYonder.Web.ReportSite.Models
{
    public class OrdersModel
    {
        public string orderID { get; set; }
    }
}

Unifac.BlueYonder.Web.ReportSite/Models/Shipments/ShipmentsModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Unifac.BlueYonder.Web.ReportSite.Models.Shipments
{
    public class ShipmentsModel
    {
        public string ShipId { get; set; }
        public string ShipStatus { get; set; }
        public string HostExtId { get; set; }
        public string CarrierCode { get; set; }
        public string DocNum { get; set; }
        public string AddDate { get; set; }
        public string CPONum { get; set; }
        public ShipmentDetailLinesModel ShipmentLines { get; set; }
        public string StopId { get; set; }
        public string CarrierMoveId { get; set; }
        public string TrailerId { get; set; }

        public string TrailerNumber { get; set; }

        public string TrailerStatus { get; set; }
        public string CloseDate { get; set; }
        public string DispatchDate { get; set; }

    }
    public class ShipmentDetailLinesModel
    {
        public string Line { get; set; }
        public string ShipmentLineId { get; set; }
        public string PartNumber { get; set; }
        public string OrderQuantity { get; set; }
        public string PickQuantity { get; set; }
        public string InProcessQuantity { get; set; }
        public string StagedQuantity { get; set; }
        public string ShippedQuantity { get; set; }
    }
}

Unifac.BlueYonder.Web.ReportSite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Unifac.BlueYonder.Web.ReportSite.Models;

namespace Unifac.BlueYonder.Web.ReportSite.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }


    }
}

Unifac.BlueYonder.Web.ReportSite/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Unifac.BlueYonder.Web.ReportSite.Models;

namespace Unifac.BlueYonder.Web.ReportSite.Controllers
{
    public class OrdersController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> GetByOrderNumber(OrdersModel ordersModel)
        {
            //pass the ordernumber to the moca api, get the results, redisplay the grid
            //this should be in a service to return the data, but for POC...

            var url = "http://localhost:61124/api/BillofLading/" + ordersModel.orderID;

            using (var httpClient = new HttpClient())
            {
                var response = await httpClient.GetAsync(url);

                var data = await response.Content.ReadAsStringAsync();

                return Ok(data);

            }
        }
    }
}

Unifac.BlueYonder.Web.ReportSite/Controllers/ShipmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Unifac.BlueYonder.Web.ReportSite.Models.Shipments;

namespace Unifac.BlueYonder.Web.ReportSite.Controllers
{
    public class ShipmentsController : Controller
    {
        public IActionResult Index(ShipmentsModel shipmentModel)
        {
            return View(shipmentModel);
        }
    }
}

Unifac.BlueYonder.Web.ReportSite/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Unifac.BlueYonder.Web.ReportSite.Controllers
{
    public class UsersController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Unifac.BlueYonder.Web.ReportSite/Views/BillofLading/Index.cshtml
@model Unifac.BlueYonder.Web.ReportSite.Models.BillofLading.BillofLadingModel

@{
    ViewData["Title"] = "Bill of Lading";
}
@{


    @*@using (Html.BeginForm("GetByOrderNumber", "BillofLading", FormMethod.Post))
    {
        @Html.TextBoxFor(model => model.billofladingID)
        @Html.ValidationMessageFor(model => model.billofladingID)
        
        <button type="submit">Lookup by Order Number</button>
    }*@
    <input id="txtOrderNumber" type="text" />
    <button id="btnDataSource" type="submit" onclick="changeDataSource(document.getElementById('txtOrderNumber').value)">Lookup by Order Number</button>
    <div id="grid"></div>
    <script>

        function changeDataSource(url) {
            var newds = "http://localhost:61124/api/BillofLading/" + url;
            var dataSource = new kendo.data.DataSource({
                transport: {
                    read: {
                        url: newds,
                        type: "GET",
                        dataType: "json",
                    }
                }
            });
            var grid = $("#grid").data("kendoGrid");
            grid.setDataSource(dataSource);
        }



        $(document).ready(function () {
            $("#grid").kendoGrid({
                dataSource: {
                    type: "json",
                    transport: {
                        read: {
                            url: "http://localhost:61124/api/BillofLading",
                            type: "GET",
                            dataType: "json",
                        }
                    }
                },
                resizable: true,
                columns: [
                    {
                        field: "wh_id",
                        title: "Warehouse ID",
                    },
                    {
                        field: "host_client_id",
                        title: "Host ID",
                    },
                    {
                        field: "trlr_num",
                        title: "Trailer Num",
                    },
                    {
                        field: "trlr_id",
                        title: "Trailer ID",
                    },
                    {
                        field: "close_dt",
                        title: "ADR ID"
                    }
                    //},
                    //{
                    //    field: "lst_dat",
                    //    title: "Last Date",
                    //},
                    //{
                    //    field: "lst_logout_dte",
                    //    title: "Last Logout Date",
                    //},
                    //{
                    //    field: "usr_dsp",
                    //    title: "User DSP",
                    //}
                ],
                filterable: true,
                //have to manually specify column widths...
                //https://www.telerik.com/forums/autofitcolumn-truncating-headings
                //AutoFitColumn truncating headings
                //http://dojo.telerik.com/OYEqa/7

                sortable: {
                    mode: "single",
                    allowUnsort: true
                },
                toolbar: ["excel"],
                excel: {
                    fileName: "Inactive Items Report.xlsx"
                },
            });
        });
    </script>

}

Unifac.BlueYonder.Web.ReportSite/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4" style="text-align:center;">Reports</h1>

    <div id="ReportLinksContainer">
        <table style="border:black 1px solid; width:100%;" cellpadding="0" cellspacing="0">
            <tr>
                <td colspan="3" style="border:black 1px solid;"> All Available Reports</td>
            </tr>
            <tr>
                <td><a asp-controller="Users" asp-action="Index">List All Users</a></td>
                @*<td><a asp-controller="BillofLading" asp-action="Index">Bill of Lading</a></td>*@
                <td><a asp-controller="Orders" asp-action="Index">Orders</a></td>
                <td><a asp-controller="Shipments" asp-action="Index">Shipments</a></td>
            </tr>
            @*<tr>
            <td><a asp-controller=" " asp-action="Index">New Report Here*</a></td>
            <td><a asp-controller=" " asp-action="Index">New Report Here*</a></td>
            <td><a asp-controller=" " asp-action="Index">New Report Here*</a></td>
        </tr>
        <tr>
            <td><a asp-controller=" " asp-action="Index">New Report Here*</a></td>
            <td><a asp-controller=" " asp-action="Index">New Report Here*</a></td>
            <td><a asp-controller=" " asp-action="Index">New Report Here*</a></td>
        </tr>*@
        </table>
    </div>
    @*<div id="grid"></div>
    <script>
        $(document).ready(function () {
            $("#grid").kendoGrid({
                dataSource: {
                    type: "json",
                    transport: {
                        read: {
                            url: "http://localhost:61124/api/Users",
                            type: "POST",
                            dataType: "json",
                        }
                    }
                },
                resizable: true,
                columns: [
                    {
                        field: "usr_dsp",
                        title: "User DSP",
                    },
                    {
                        field: "last_name",
                        title: "Last Name"
                    }
                ],
                filterable: true,
                //have to manually specify column widths...
                //https://www.telerik.com/forums/autofitcolumn-truncating-headings
                //AutoFitColumn truncating headings
                //http://dojo.telerik.com/OYEqa/7
                resizable: true,
                sortable: {
                    mode: "single",
                    allowUnsort: true
                },
                toolbar: ["excel"],
                excel: {
                    fileName: "Inactive Items Report.xlsx"
                },
            });
        });
    </script>*@
  
</div>

Unifac.BlueYonder.Web.ReportSite/Views/Orders/Index.cshtml
@model Unifac.BlueYonder.Web.ReportSite.Models.OrdersModel


<input id="txtOrderNumber" type="text" />
<button id="btnDataSource" type="submit" onclick="changeDataSource(document.getElementById('txtOrderNumber').value)">Lookup by Order Number</button>
<div id="grid"></div>
<script>

    


    $(document).ready(function () {
        $("#grid").kendoGrid({
            dataSource: {
                type: "json",
                transport: {
                    read: {
                        url: "http://localhost:61124/api/orders",
                        type: "GET",
                        dataType: "json",
                    }
                }
            },
            resizable: true,
            columns: [
                {
                    field: "orderNumber",
                    title: "Order Number",
                },
                {
                    field: "warehouseId",
                    title: "Warehouse ID",
                },
                {
                    field: "btCustomer",
                    title: "BT Customer",
                },
                {
                    field: "stCustomer",
                    title: "ST Customer",
                },
                {
                    field: "rtCustomer",
                    title: "RT Customer"
                },
                {
                    field: "orderType",
                    title: "Order Type"
                },
                {
                    field: "enteredDate",
                    title: "Enter Date"
                },
                {
                    field: "addDate",
                    title: "Add Date"
                },
                {
                    field: "cpoNum",
                    title: "CPO Number"
                }

                //},
                //{
                //    field: "lst_dat",
                //    title: "Last Date",
                //},
                //{
                //    field: "lst_logout_dte",
                //    title: "Last Logout Date",
                //},
                //{
                //    field: "usr_dsp",
                //    title: "User DSP",
                //}
            ],
            filterable: true,
            //have to manually specify column widths...
            //https://www.telerik.com/forums/autofitcolumn-truncating-headings
            //AutoFitColumn truncating headings
            //http://dojo.telerik.com/OYEqa/7

            sortable: {
                mode: "single",
                allowUnsort: true
            },
            toolbar: ["excel"],
            excel: {
                fileName: "Inactive Items Report.xlsx"
            },
        });
    });

    function changeDataSource(url) {
        var newds = "http://localhost:61124/api/orders/search?orderNumber=".concat(url);
        var dataSource = new kendo.data.DataSource({
            transport: {
                read: {
                    url: newds,
                    type: "GET",
                    dataType: "json"
                }
            }
        });
        var grid = $("#grid").data("kendoGrid");
        grid.setDataSource(dataSource);
    }

</script>

Unifac.BlueYonder.Web.ReportSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Unifac.Web.BY.ReportSite</title>

    <link href="https://kendo.cdn.telerik.com/2020.2.617/styles/kendo.common.min.css" rel="stylesheet" />
    <link href="https://kendo.cdn.telerik.com/2020.2.617/styles/kendo.default.min.css" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-1.12.3.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2020.2.617/js/kendo.all.min.js"></script>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                @*Returns the welcome message in Home/index.cshtml *@
                <a class="navbar-brand" asp-area="" asp-controller="Users" asp-action="Index">Unifac.Web.BY.ReportSite</a>
                
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            @*anchor link to the home page, calls the Home Controller's Index method'*@
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            @*anchor link to the home controller's 'privacy' method'*@
                            @*<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>*@
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Unifac.Web.BY.ReportSite - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)*@
</body>
</html>

Unifac.BlueYonder.Web.ReportSite/Views/Shipments/Index.cshtml
@*@model Unifac.BlueYonder.Web.ReportSite.Models.Shipments.ShipmentsModel*@

<style>
    .k-detail-cell .k-tabstrip .k-content {
        padding: 0.2em;
    }

    .shipment-details ul {
        list-style: none;
        font-style: italic;
        margin: 15px;
        padding: 0;
    }

        .shipment-details ul li {
            margin: 0;
            line-height: 1.7em;
        }

    .shipment-details label {
        display: inline-block;
        width: 90px;
        padding-right: 10px;
        text-align: right;
        font-style: normal;
        font-weight: bold;
    }
</style>


<table>
    <tr>
        <td><label>Trailer Number</label></td>
        <td><input id="txtTrailerNumber" type="text" /></td>
        <td><label>Order Number</label></td>
        <td>
            <input id="txtOrderNumber" type="text" />
        </td>
    </tr>
    @*<tr>
       
    </tr>*@
    <tr>
        <td>
            <label>Document Number</label>
        </td>
        <td>
            <input id="txtdocumentNumber" type="text" />
        </td>
        <td>
            <label>Dispatch Date</label>
        </td>
        <td>
            <input id="txtdispatchDate" type="text" />
        </td>
        <td>
            <label>Shipment Id</label>
        </td>
        <td>
            <input id="txtshipmentId" type="text" />
        </td>
    </tr>
    @*<tr>
        
    </tr>
    <tr>
       
    </tr>*@
    <tr>
        <td>
            <label>Begin Dispatch Date</label>
        </td>
        <td>
            <input id="txtbegindispatchDate" type="text" />
        </td>
    </tr>
    <tr>
        <td>
            <label>End Dispatch Date</label>
        </td>
        <td>
            <input id="txtenddispatchDate" type="text" />
        </td>
    </tr>
</table>




<button id="btnDataSource" type="submit"
        onclick="changeDataSource(document.getElementById('txtTrailerNumber').value
    , document.getElementById('txtOrderNumber').value
    , document.getElementById('txtdocumentNumber').value
    , document.getElementById('txtdispatchDate').value
    , document.getElementById('txtshipmentId').value
    , document.getElementById('txtbegindispatchDate').value
    , document.getElementById('txtenddispatchDate').value)">
    Search
</button>

<div id="grid"></div>

<script type="text/x-kendo-template" id="template">
    <div class="detailTabstrip">
        <ul>
            <li class="k-state-active">
                Shipment Line Detail
            </li>
            @*<li><label>Line :</label>#= shipmentLines #</li>*@

        </ul>
        <div>
            <div class="shipmentLinesDetail"></div>
        </div>
        <div>
            <div class='shipment-details'>
                <ul>
                    @*<li><label>City:</label>#= shipmentLines.line #</li> *@

                </ul>
            </div>
        </div>
    </div>
</script>

<script>

    // set the default view to be a specific trailer number
    $(document).ready(function () {

        $("#grid").kendoGrid({
            dataSource: {
                type: "json",
                transport: {
                    read: {
                        url: "http://localhost:61124/api/shipments",
                        type: "GET",
                        dataType: "json"
                    }
                },
                pageSize: 5,
                serverPaging: true,
                serverFiltering: true,
                serverSorting: true
                
               
            },
            pageable: {
                refresh: true,
                pageSizes: 5,

            },
            detailTemplate: kendo.template($("#template").html()),
            detailInit: detailInit,
            dataBound: function () {
                this.expandRow(this.tbody.find("tr.k-master-row").first());
            },
            resizable: true,
            columns: [
                {
                    field: "shipId",
                    title: "Shipment ID",
                },
                {
                    field: "orderNumber",
                    title: "Order Number",
                },
                {
                    field: "shipStatus",
                    title: "Ship Status",
                },
                {
                    field: "hostExtId",
                    title: "Host Ext Id",
                },
                {
                    field: "carrierCode",
                    title: "Carrier Code",
                },
                {
                    field: "docNum",
                    title: "Doc Num",
                },
                {
                    field: "addDate",
                    title: "Add Date",
                },
               
                
            ],
            filterable: true,
            //have to manually specify column widths...
            //https://www.telerik.com/forums/autofitcolumn-truncating-headings
            //AutoFitColumn truncating headings
            //http://dojo.telerik.com/OYEqa/7

            sortable: {
                mode: "single",
                allowUnsort: true
            },
            toolbar: ["excel"],
            excel: {
                fileName: "Inactive Items Report.xlsx"
            },
        });
    });

    function detailInit(e) {
        var detailRow = e.detailRow;

        detailRow.find(".detailTabstrip").kendoTabStrip({
            animation: {
                open: { effects: "fadeIn" }
            }
        });
        var ordnum = e.data.orderNumber;
        var url = "http://localhost:61124/api/shipments/orderdetail/" + ordnum; 
        detailRow.find(".shipmentLinesDetail").kendoGrid({
            dataSource: {
                type: "json",
                transport: {
                    read: url,
                    type: "GET",
                    dataType: "json"
                },
                serverPaging: true,
                serverSorting: true,
                serverFiltering: true,
                pageSize: 5
                //,filter: { field: "orderNumber", operator: "eq", value: e.data.orderNumber }
                
            },
            scrollable: false,
            sortable: true,
            pageable: true,
            columns: [
                
                { field: "line", title: "Line", width: "110px" },
                { field: "shipmentLineId", title: "Shipment Line ID", width: "110px" },
                { field: "partNumber", title: "Part No.", width: "110px" },
                { field: "orderQuantity", title: "Order Qty", width: "110px" },
                { field: "pickQuantity", title: "Pick Qty", width: "110px" }
            ]
        });
    }

    /* trailer number required, ordernumber, documentnumber, dispatchdate */
    function changeDataSource(trailerNumber
        , orderNumber
        , documentNumber
        , dispatchDate
        , shipmentId
        , begindispatchDate
        , enddispatchDate) {

        var queryparams = "";

        if (trailerNumber != "") {
            if (queryparams != "")
                queryparams = queryparams + trailerNumber;
            else
                queryparams = queryparams + "?trailerNumber=" + trailerNumber;
        }
        //else {
        //    document.getElementById('txtTrailerNumber').value = "Trailer Number Required";
        //    return 0;
        //}

        if (orderNumber != "") {
            if (queryparams != "")
                queryparams = queryparams + "&orderNumber=" + orderNumber;
            else
                queryparams = queryparams + "?orderNumber=" + orderNumber;

        }
        if (documentNumber != "") {
            if (queryparams != "")
                queryparams = queryparams + "&documentNumber=" + documentNumber;
            else
                queryparams = queryparams + "?documentNumber=" + documentNumber;

        }
        if (dispatchDate != "") {
            if (queryparams != "")
                queryparams = queryparams + "&dispatchDate=" + encodeURIComponent(dispatchDate);
            else
                queryparams = queryparams + "?dispatchDate=" + encodeURIComponent(dispatchDate);

        }
        if (orderNumber != "") {
            if (queryparams != "")
                queryparams = queryparams + "&orderNumber=" + orderNumber;
            else
                queryparams = queryparams + "?orderNumber=" + orderNumber;

        }
        if (shipmentId != "") {
            if (queryparams != "")
                queryparams = queryparams + "&shipmentId=" + shipmentId;
            else
                queryparams = queryparams + "?shipmentId=" + shipmentId;

        }
        if (begindispatchDate != "" & enddispatchDate != "") {
            if (queryparams != "")
                queryparams = queryparams + "&begindispatchDate=" + encodeURIComponent(begindispatchDate) + "&enddispatchDate=" + encodeURIComponent(enddispatchDate);
            else
                queryparams = queryparams + "?" + "&begindispatchDate=" + encodeURIComponent(begindispatchDate) + "&enddispatchDate=" + encodeURIComponent(enddispatchDate);

        }



        var newds = "http://localhost:61124/api/shipments" + queryparams;
        var dataSource = new kendo.data.DataSource({
            transport: {
                read: {
                    url: newds,
                    type: "GET",
                    dataType: "json"
                }
                ,
            }
        });
        var grid = $("#grid").data("kendoGrid");
        grid.setDataSource(dataSource);
    }

</script>

Unifac.BlueYonder.Web.ReportSite/Views/Users/Index.cshtml
@{
    ViewData["Title"] = "Users";

}
@{
    <div id="grid"></div>
    <script>
        $(document).ready(function () {
            $("#grid").kendoGrid({
                dataSource: {
                    type: "json",
                    transport: {
                        read: {
                            url: "http://localhost:61124/api/users",
                            type: "GET",
                            dataType: "json",
                        }
                    }
                },
                resizable: true,
                columns: [
                    {
                        field: "firstname",
                        title: "First Name",
                    },
                    {
                        field: "lastname",
                        title: "Last Name",
                    },
                    {
                        field: "userId",
                        title: "User ID",
                    },
                    {
                        field: "loginId",
                        title: "Login ID",
                    },
                    {
                        field: "adrId",
                        title: "ADR ID",
                    },
                    {
                        field: "lstDate",
                        title: "Last Date",
                    },
                    {
                        field: "lastLogoutDate",
                        title: "Last Logout Date",
                    },
                    {
                        field: "userDsp",
                        title: "User DSP",
                    }
                ],
                filterable: true,
                //have to manually specify column widths...
                //https://www.telerik.com/forums/autofitcolumn-truncating-headings
                //AutoFitColumn truncating headings
                //http://dojo.telerik.com/OYEqa/7
                resizable: true,
                sortable: {
                    mode: "single",
                    allowUnsort: true
                },
                toolbar: ["excel"],
                excel: {
                    fileName: "Inactive Items Report.xlsx"
                },
            });
        });
    </script>

}